version: "2"

services:
  web:
    build:
      context: .
      dockerfile: ./main/Dockerfile
    container_name: main
    working_dir: /app
    command: bundle exec hanami server
    ports:
      - 2300:2300
    volumes:
      - ./main:/app
  preact_client:
    build:
      context: .
      dockerfile: ./preact_client/Dockerfile
    container_name: preact_client
    working_dir: /app
    command: yarn start
    ports:
      - 8080:8080
    volumes:
      - ./preact_client:/app
      - /app/node_modules
  preact_standalone:
    build:
      context: .
      dockerfile: ./preact_standalone/Dockerfile
    container_name: preact_standalone
    working_dir: /app
    command: yarn start
    ports:
      - 9090:9090
    volumes:
      - ./preact_standalone:/app
      - /app/node_modules
